### ISSUE TITLE
Plankton "data conversion" from C# lib

### ISSUE THREAD

**Issue by adrier** [pearswj/Plankton#6]
Hi Will,

I am writing you here because I have an issue with the C# library.
I wrote about it here: http://www.grasshopper3d.com/forum/topics/plankton-data-conversion
I tried to install several versions of Plankton, even tried those from the MeshEdit package but can not solve the issue regarding exporting a planktonmesh from a C# component to the Deconstruct PlanktonMesh GH component.

My GH definition is uploaded on the GH forum. Please let me know if you need more information.

Thank you

Adrien

**Comment by pearswj** [comment]
Hi Adrien,

I experienced the same bug as you. I'll add it to the McNeel issue tracker...

For the sake of getting the script to work, I tried converting it to Python... The problem went away!

[Example_Adjacent_Face_1_py.gh.zip](https://github.com/pearswj/Plankton/files/1211784/Example_Adjacent_Face_1_py.gh.zip)


-- Will

**Comment by Dan-Piker** [comment]
Hi Adrien,

Have you tried turning off the COFF option in GrasshopperDeveloperSettings?

Dan

**Comment by pearswj** [comment]
>Have you tried turning off the COFF option in GrasshopperDeveloperSettings?

I just tested this and, after restarting Rhino, it works!

**Comment by adrier** [comment]
I works here too! Thank you Dan, and thanks Will for the Python conversion!
